name: Node.js Package
on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: "production"
      url: "https://www.npmjs.com/package/github-pewpew"
    steps:
      - uses: actions/checkout@v7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v7
        with:
          node-version: "24.x"
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      # Run tests
      - run: npm test
      # Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
